name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: print runner specs
      run: lscpu && free -g
    - name: Build the Docker image
      run: docker build . --file Containerfile.base --tag docker.io/diliprenkila/lightspeed:base
